steps:
  - name: ":anyscale: hello world"
    timeout: 10
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            ANYSCALE_CLI_TOKEN: "anyscale_cli_token"
      - csivanich/anyscale-job:
          file: "job.yaml"
          name: "test job"
          description: "testing plugin"
