#!/usr/bin/env bash

if [[ -n "$BUILDKITE_PLUGIN_ANYSCALE_JOB_DEBUG" ]];then
    set -x
fi

set -euo pipefail

fail(){
    "ERROR: $*"
    exit 1
}

WORKING_DIR="${WORKING_DIR:-$(pwd)}"
PREFIX="BUILDKITE_PLUGIN_ANYSCALE_JOB_"
env | grep "$PREFIX"

file="$BUILDKITE_PLUGIN_ANYSCALE_JOB_FILE"
name="$BUILDKITE_PLUGIN_ANYSCALE_JOB_NAME"
description="$BUILDKITE_PLUGIN_ANYSCALE_JOB_DESCRIPTION"

if [[ -z "$file" ]];then
    fail "Missing 'file' property"
fi

cat "$file"

if [[ -n "$name" ]];then
    echo "$name"
fi

if [[ -n "$description" ]];then
    echo "$description"
fi


echo "~~~ Loading credentials"
CREDENTIALS_FILE="${BUILDKITE_PLUGIN_ANYSCALE_JOB_CREDENTIALS_FILE:-}"

test -r "$CREDENTIALS_FILE" || fail "Could not read credentials file: $CREDENTIALS_FILE"
if [[ -n "$BUILDKITE_PLUGIN_ANYSCALE_JOB_DEBUG" ]];then
    set +x
fi
ANYSCALE_CLI_TOKEN="$(cat "$CREDENTIALS_FILE")"
export ANYSCALE_CLI_TOKEN
if [[ -n "$BUILDKITE_PLUGIN_ANYSCALE_JOB_DEBUG" ]];then
    set -x
fi

echo "+++ :anyscale: Running Job $name"
docker run \
    -it \
    -e ANYSCALE_HOST=https://console.anyscale.com \
    -e ANYSCALE_CLI_TOKEN \
    --entrypoint anyscale \
    -v "$WORKING_DIR":/job \
    "$BUILDKITE_PLUGIN_ANYSCALE_JOB_IMAGE" \
    job submit \
        --wait \
        --follow \
        --name "$name" \
        --description "$description" \
        -f "/job/$file"
