#!/usr/bin/env bash

if [[ -n "$BUILDKITE_PLUGIN_ANYSCALE_JOB_DEBUG" ]];then
    set -x
fi

set -euo pipefail

fail(){
    "ERROR: $*"
    exit 1
}

PREFIX="BUILDKITE_PLUGIN_ANYSCALE_JOB_"
env | grep "$PREFIX"

file="$BUILDKITE_PLUGIN_ANYSCALE_JOB_FILE"
name="$BUILDKITE_PLUGIN_ANYSCALE_JOB_NAME"
description="$BUILDKITE_PLUGIN_ANYSCALE_JOB_DESCRIPTION"

if [[ -z "$file" ]];then
    fail "Missing 'file' property"
fi

cat "$file"

if [[ -n "$name" ]];then
    echo "$name"
fi

if [[ -n "$description" ]];then
    echo "$description"
fi

job_submit_local(){
    echo "~~~ :anyscale: Installing CLI"
    pip3 install -U anyscale
    export PATH="/var/lib/buildkite-agent/.local/bin/:$PATH"

    if ! anyscale --version;then
        fail "Cannot find Anyscale CLI post-install"
    fi

    echo "~~~ :anyscale: Running Job"
    anyscale job submit \
        --wait \
        --name "$name" \
        --description "$description" \
        -f "$file"
}

job_submit_docker(){
    docker run \
        -it \
        -e ANYSCALE_HOST=https://console.anyscale.com \
        --entrypoint anyscale \
        -v "$(pwd)":/job \
        -v "$CREDENTIALS_FILE:/home/ray/anyscale/.credentials.json" \
        anyscale/ray \
        job submit \
            --wait \
            --name "$name" \
            --description "$description" \
            -f "/job/$file"
}

login_docker(){
    docker run \
        -it \
        --entrypoint anyscale \
        -v "$(pwd)":/job \
        anyscale/ray \
        login
}

check_credentials(){
    docker run \
        -it \
        -e ANYSCALE_HOST=https://console.anyscale.com \
        --entrypoint anyscale \
        -v "$CREDENTIALS_FILE:/home/ray/.anyscale/credentials.json" \
        anyscale/ray \
        cloud list
}

echo "~~~ Loading credentials"
CREDENTIALS_FILE="${BUILDKITE_PLUGIN_ANYSCALE_JOB_CREDENTIALS_FILE:-}"

if [[ -z "$CREDENTIALS_FILE" ]];then
    echo "+++ Login using this link"
    login_docker
else
    test -r "$CREDENTIALS_FILE" || fail "Could not read credentials file: $CREDENTIALS_FILE"
    check_credentials
fi

echo "--- :anyscale: Running Job"
job_submit_docker
