#!/usr/bin/env bash

set -euo pipefail

fail(){
    "ERROR: $*"
    exit 1
}

PREFIX="BUILDKITE_PLUGIN_ANYSCALE_JOB_"
env | grep "$PREFIX"

file="$BUILDKITE_PLUGIN_ANYSCALE_JOB_FILE"
name="$BUILDKITE_PLUGIN_ANYSCALE_JOB_NAME"
description="$BUILDKITE_PLUGIN_ANYSCALE_JOB_DESCRIPTION"

if [[ -z "$file" ]];then
    fail "Missing 'file' property"
fi

cat "$file"

if [[ -n "$name" ]];then
    echo "$name"
fi

if [[ -n "$description" ]];then
    echo "$description"
fi

job_submit_local(){
    echo "~~~ :anyscale: Installing CLI"
    pip3 install -U anyscale
    export PATH="/var/lib/buildkite-agent/.local/bin/:$PATH"

    if ! anyscale --version;then
        fail "Cannot find Anyscale CLI post-install"
    fi

    echo "~~~ :anyscale: Running Job"
    anyscale job submit \
        --wait \
        --name "$name" \
        --description "$description" \
        -f "$file"
}

job_submit_docker(){
    echo "~~~ :anyscale: Pulling Image"
    docker pull anyscale/ray
}

job_submit_docker
